In [27]:
import pandas
import numpy

In [41]:
df_1127 = pandas.read_csv('result_1127.csv')
df_2530 = pandas.read_csv('result_2530_yortz2.csv')
df_281 = pandas.read_csv('result_281_yortz.csv')

In [42]:
out_df = pandas.concat([df_1127, df_2530, df_281])

In [43]:
out_df = out_df.set_index('ip_id')

In [44]:
out_df

          prob1
ip_id
6362   0.056166
6363   0.049581
6365   0.049581
6366   0.056166
6372   0.056166
6373   0.049581
6374   0.049581
6375   0.049581
6377   0.056166
6380   0.056166
6388   0.034038
6389   0.056166
6390   0.056166
6392   0.056166
6393   0.056166
6395   0.056166
6396   0.034038
6397   0.049581
6403   0.079775
6404   0.049581
6415   0.034038
6421   0.079775
6424   0.056166
6426   0.056166
6427   0.056166
6428   0.034038
6430   0.049581
6434   0.079282
6439   0.049581
6443   0.049581
...         ...
9955   0.044329
9984   0.697251
9990   0.044329
10010  0.044260
10019  0.044329
10033  0.012726
10035  0.607746
10045  0.012726
10047  0.044329
10050  0.012726
10052  0.012726
10054  0.012726
10071  0.077860
10086  0.012726
10091  0.044329
10097  0.012726
10121  0.044329
10127  0.044260
10141  0.044329
10159  0.012726
10200  0.044329
10202  0.044260
10233  0.012726
10244  0.060866
10262  0.060866
10264  0.012726
10266  0.077860
10277  0.012726
10289  0.303520
10298  0.044329

[3938 rows x 1 columns]

In [8]:
id_test = pandas.read_csv('data/y_test_index.csv')

In [20]:
id_281 = [ipid for ipid in id_test['ip_id'] if ipid not in out_df['ip_id'].values]

In [33]:
out_df['ip_id'].unique()

array([ 6362,  6363,  6365, ..., 10277, 10289, 10298])

In [15]:
id_test.shape

(3938, 1)

In [18]:
6372 not in out_df['ip_id'].values

False

In [45]:
out_df.sort_index().to_csv('2_TJ2018-AUDITION-11510.csv', index=False)

In [46]:
df_1127 = pandas.read_csv('result_1127_yortz.csv')
df_2530 = pandas.read_csv('result_2530_yortz2.csv')
df_281 = pandas.read_csv('result_281_yortz.csv')
out_df = pandas.concat([df_1127, df_2530, df_281])
out_df = out_df.set_index('ip_id')
out_df.sort_index().to_csv('3_TJ2018-AUDITION-11510.csv', index=False)

In [47]:
df_1127 = pandas.read_csv('result_1127_yortz.csv')
df_2530 = pandas.read_csv('yortz_result_2530_3.csv')
df_281 = pandas.read_csv('result_281_yortz.csv')
out_df = pandas.concat([df_1127, df_2530, df_281])
out_df = out_df.set_index('ip_id')
out_df.sort_index().to_csv('4_TJ2018-AUDITION-11510.csv', index=False)